version: "3.8"

services:

  db:
    build: src/SqlDeploy.Database
    ports:
      - 14333:1433

  # compose file args to optionally not do below?
  migrate_app:
      build: src/SqlDeploy
      environment:
        - SQLDEPLOY_TARGET__SERVER=db
        - SQLDEPLOY_TARGET__DATABASE=TestDeploy
        - SQLDEPLOY_TARGET__USERID=sa
        - SQLDEPLOY_TARGET__PASSWORD=abc!!123
      depends_on:
        - db
