FROM mcr.microsoft.com/mssql/server:2019-latest

ENV ACCEPT_EULA=Y \
    SA_PASSWORD=abc!!123 \
    MSSQL_AGENT_ENABLED=1 \
    MSSQL_PID=Enterprise

EXPOSE 1433

CMD /opt/mssql/bin/sqlservr
